### PR TITLE
Add erlyberly

### PR DESCRIPTION
**Pull request by aboroska**
erlyberly is not widespread (yet). So, maybe should it not belong here. On the other hand it has some nice and advanced features that I like and other tools lack. Please, decide yourself, I will not be offended if you don't take it. (Hint: run the binary release for a try if you haven't used it yet.)

### CODE REVIEW

**Comment by unbalancedparentheses** [comment]
@aboroska I have never used it but it seems cool and serious work. Have you tried it?

**Comment by aboroska** [comment]
Me and at least a few others use it frequently and love it. My favourite features:
- Presents all modules/functions in searchable form (one click tracing)
- Very easily filterable logs
- Uses different colours to facilitate spotting of exceptions/errors.
- Remembers the last traced node, no need to reenter nodename/cookie. 
- Digs usable information from debug_info compiled beams. For example to show gen_server state with record syntax if applicable or the source code of the traced function.

@andytill could elaborate.

Note, that I am biased because I contributed some minor parts. Try it out. :)

**Comment by unbalancedparentheses** [comment]
Awesome. I will add it, and also I will try it :facepunch: !

**Comment by unbalancedparentheses** [comment]
Done: http://spawnedshelter.com/#debugging-tracing-and-logging.

I add it by myself because I refactored the markdown. I added it a new section called profilling and this PR had conflicts because of that.

**Pull request closed without merging**
